#!/bin/sh
#
# Starts inetd.
#

start() {
	printf "Starting inetd: "
	start-stop-daemon -S -q -p /var/run/inetd.pid \
		-x /usr/sbin/inetd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping inetd: "
	start-stop-daemon -K -q -p /var/run/inetd.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
