// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Futuristic_Ebike

#include "ui.h"
#include <stdio.h>

void pin_clicked(lv_event_t * e)
{
	static char pin[4];
	static int pin_index = 0;
	lv_obj_t * btn = lv_event_get_target(e);

	if (btn == ui_Button_PinX1) {
		if (pin_index < 4) {
			printf("please enter 4 digits\n");
		} else {
			printf("entered pin: %d %d %d %d\n", pin[0], pin[1], pin[2], pin[3]);
			pin_index = 0;
		}
	} else if (btn == ui_Button_PinX) {
		pin_index = 0;
	} else {
		if (pin_index == 4) {
			return;
		}
		if (btn == ui_Button_Pin0) {
			pin[pin_index] = 0;
		} else if (btn == ui_Button_Pin1) {
			pin[pin_index] = 1;
		} else if (btn == ui_Button_Pin2) {
			pin[pin_index] = 2;
		} else if (btn == ui_Button_Pin3) {
			pin[pin_index] = 3;
		} else if (btn == ui_Button_Pin4) {
			pin[pin_index] = 4;
		} else if (btn == ui_Button_Pin5) {
			pin[pin_index] = 5;
		} else if (btn == ui_Button_Pin6) {
			pin[pin_index] = 6;
		} else if (btn == ui_Button_Pin7) {
			pin[pin_index] = 7;
		} else if (btn == ui_Button_Pin8) {
			pin[pin_index] = 8;
		} else if (btn == ui_Button_Pin9) {
			pin[pin_index] = 9;
		}
		pin_index ++;
	}
}
